// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCun00euRpbju_BjNMokRBL2OhyVHZK5-w',
    appId: '1:976668857536:web:11333a3aee5deac52ec925',
    messagingSenderId: '976668857536',
    projectId: 'portfolio-99b6f',
    authDomain: 'portfolio-99b6f.firebaseapp.com',
    storageBucket: 'portfolio-99b6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2TkT9gZMupB65wrn33EYzHNEGIVcg3A',
    appId: '1:976668857536:android:bc46549e3ed577602ec925',
    messagingSenderId: '976668857536',
    projectId: 'portfolio-99b6f',
    storageBucket: 'portfolio-99b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3DrGzySxOS4GNpXoYsGsgAhZd76yCO9w',
    appId: '1:976668857536:ios:a9638875b7bd2ff92ec925',
    messagingSenderId: '976668857536',
    projectId: 'portfolio-99b6f',
    storageBucket: 'portfolio-99b6f.appspot.com',
    iosClientId: '976668857536-rsre0oe7qqd02n3ta2qkb4um7snlog2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPortfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3DrGzySxOS4GNpXoYsGsgAhZd76yCO9w',
    appId: '1:976668857536:ios:db84cd200062cfad2ec925',
    messagingSenderId: '976668857536',
    projectId: 'portfolio-99b6f',
    storageBucket: 'portfolio-99b6f.appspot.com',
    iosClientId: '976668857536-uigl1cvh8fv46mai31ruuq44elj9742u.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioWebsite',
  );
}
